[package]
name = "dbn-macros"
authors = ["Databento <support@databento.com>"]
version = "0.11.0"
edition = "2021"
description = "Proc macros for dbn crate"
license = "Apache-2.0"
repository = "https://github.com/databento/dbn"

[lib]
proc-macro = true

[dependencies]
# Get name of current crate in macros, like $crate in macro_rules macros
proc-macro-crate = "1.3.1"
proc-macro2 = "1.0"
# Convert code to token streams
quote = "1.0"
# Token parsing
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
trybuild = "1.0.82"
