[package]
name = "dbn-macros"
authors = ["Databento <support@databento.com>"]
version = "0.5.1"
edition = "2021"
description = "Proc macros for dbn crate"
license = "Apache-2.0"
repository = "https://github.com/databento/dbn"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
