[package]
name = "dbn-macros"
authors = ["Databento <support@databento.com>"]
version = "0.14.1"
edition = "2021"
description = "Proc macros for dbn crate"
license = "Apache-2.0"
repository = "https://github.com/databento/dbn"

[lib]
proc-macro = true

[dependencies]
# Get name of current crate in macros, like $crate in macro_rules macros
proc-macro-crate = "2.0.0"
proc-macro2 = "1.0.69"
# Convert code to token streams
quote = "1.0.33"
# Token parsing
syn = { version = "2.0.39", features = ["full"] }

[dev-dependencies]
csv = "1"
dbn = { path = "../dbn" }
trybuild = "1.0.85"
