[workspace]
members = [
  "c",
  "python",
  "rust/dbn-cli",
  "rust/dbn-macros",
  "rust/dbn"
]
resolver = "2"

[workspace.package]
authors = ["Databento <support@databento.com>"]
edition = "2021"
version = "0.24.0"
documentation = "https://databento.com/docs"
repository = "https://github.com/databento/dbn"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.94"
csv = "1.3"
pyo3 = "0.22.6"
pyo3-build-config = "0.22.6"
rstest = "0.23.0"
serde = { version = "1.0", features = ["derive"] }
time = ">=0.3.35"
zstd = "0.13"
