[package]
name = "dbn-cli"
authors = ["Databento <support@databento.com>"]
version = "0.13.0"
edition = "2021"
description = "Command-line utility for converting Databento Binary Encoding (DBN) files to text-based formats"
default-run = "dbn"
license = "Apache-2.0"
repository = "https://github.com/databento/dbn"
keywords = ["market-data", "json", "csv", "conversion", "encoding"]
# see https://crates.io/category_slugs
categories = ["command-line-utilities", "encoding"]

[[bin]]
name = "dbn"
path = "src/main.rs"

[dependencies]
# Databento common DBN library
dbn = { path = "../dbn", version = "=0.13.0", default-features = false }

# Error handling
anyhow = "1.0"
# CLI argument parsing
clap = { version = "4.4", features = ["derive"] }
# deserialization for CLI args
serde = { version = "1.0", features = ["derive"] }
zstd = "0.13"

[dev-dependencies]
# CLI integration tests
assert_cmd = "2.0.12"
# assert_cmd companion
predicates = "3.0.4"
rstest = "0.18.2"
# A library for managing temporary files and directories
tempfile = "3.8.0"
