[package]
name = "dbn-cli"
description = "Command-line utility for converting Databento Binary Encoding (DBN) files to text-based formats"
default-run = "dbn"
keywords = ["market-data", "json", "csv", "conversion", "encoding"]
# see https://crates.io/category_slugs
categories = ["command-line-utilities", "encoding"]
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "dbn"
path = "src/main.rs"

[dependencies]
# Databento common DBN library
dbn = { path = "../dbn", version = "=0.15.1", default-features = false }

# Error handling
anyhow = "1.0"
# CLI argument parsing
clap = { version = "4.4", features = ["derive", "wrap_help"] }
# deserialization for CLI args
serde = { version = "1.0", features = ["derive"] }
# Compression
zstd = "0.13"

[dev-dependencies]
# CLI integration tests
assert_cmd = "2.0.13"
# assert_cmd companion
predicates = "3.0.4"
rstest = "0.18.2"
# A library for managing temporary files and directories
tempfile = "3.9.0"
