name: release

on:
  workflow_run:
    workflows: [build]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  tag-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ github.event.workflow_dispatch }}
    name: tag-release - Python 3.12 (ubuntu-latest)
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      # Set release output variables
      - name: Set output
        id: vars
        run: |
          echo "TAG_NAME=v$(scripts/get_version.sh)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(scripts/get_version.sh)" >> $GITHUB_ENV
          echo "## Release notes" > NOTES.md
          sed -n '/^## /{n; :a; /^## /q; p; n; ba}' CHANGELOG.md >> NOTES.md

      # Create GitHub release
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          append_body: true
          body_path: ./NOTES.md
          prerelease: false

  macos-python-release:
    needs: [tag-release]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust
        run: rustup toolchain add --profile minimal stable --component clippy,rustfmt

      # Cargo setup
      - name: Set up Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-x86_64-cargo-${{ hashFiles('Cargo.lock') }}

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels - x86_64
        uses: messense/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist --manifest-path python/Cargo.toml --interpreter python${{ matrix.python-version }}

      - name: Build wheels - universal2
        uses: messense/maturin-action@v1
        with:
          args: --release --target universal2-apple-darwin --out dist --manifest-path python/Cargo.toml --interpreter python${{ matrix.python-version }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-macos-${{ matrix.python-version }}
          path: dist

  windows-python-release:
    needs: [tag-release]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust
        run: rustup toolchain add --profile minimal stable --component clippy,rustfmt

      # Cargo setup
      - name: Set up Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-x86_64-cargo-${{ hashFiles('Cargo.lock') }}

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          target: x64
          args: --release --out dist --manifest-path python/Cargo.toml --interpreter python${{ matrix.python-version }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-windows-${{ matrix.python-version }}
          path: dist

  linux-python-release:
    needs: [tag-release]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        target: [x86_64, aarch64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust
        run: rustup toolchain add --profile minimal stable --component clippy,rustfmt

      # Cargo setup
      - name: Set up Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('Cargo.lock') }}

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: --release --out dist --manifest-path python/Cargo.toml --interpreter python${{ matrix.python-version }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-linux-${{ matrix.target }}-${{ matrix.python-version }}
          path: dist

  linux-musl-python-release:
    needs: [tag-release]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust
        run: rustup toolchain add --profile minimal stable --component clippy,rustfmt

      # Cargo setup
      - name: Set up Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('Cargo.lock') }}

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: musllinux_1_2
          args: --release --out dist --manifest-path python/Cargo.toml --interpreter python${{ matrix.python-version }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-linux-musl-${{ matrix.target }}-${{ matrix.python-version }}
          path: dist

  publish-py:
    runs-on: ubuntu-latest
    needs:
      [
        tag-release,
        macos-python-release,
        windows-python-release,
        linux-python-release,
        linux-musl-python-release,
      ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          merge-multiple: true
      # Install publish dependencies
      - name: Install publish dependencies
        # Upgrade packaging here to try to resolve https://github.com/pypa/twine/issues/1216
        run: python -m pip install --upgrade packaging twine

      - name: Publish to PyPI
        id: publish-to-pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload *

  publish-rs:
    runs-on: ubuntu-latest
    needs:
      [
        tag-release,
        macos-python-release,
        windows-python-release,
        linux-python-release,
        linux-musl-python-release,
      ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust
        run: rustup toolchain add --profile minimal stable --component clippy,rustfmt

      # Cargo setup
      - name: Set up Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Publish dbn-macros to crates.io
        run: cargo publish --token ${CARGO_REGISTRY_TOKEN} --package dbn-macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish dbn to crates.io
        run: cargo publish --token ${CARGO_REGISTRY_TOKEN} --package dbn
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish dbn-cli to crates.io
        run: cargo publish --token ${CARGO_REGISTRY_TOKEN} --package dbn-cli
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  build-cli-artifacts:
    name: build-release
    needs: [tag-release]
    runs-on: ${{ matrix.os }}
    env:
      TARGET_FLAGS:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
        - os: ubuntu-latest
          target: aarch64-unknown-linux-musl
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - os: macos-latest
          target: x86_64-apple-darwin
        - os: macos-latest
          target: x86_64-apple-darwin
        - os: macos-latest
          target: aarch64-apple-darwin
        - os: windows-latest
          target: aarch64-pc-windows-msvc
        - os: windows-latest
          target: x86_64-pc-windows-gnu
        - os: windows-latest
          target: x86_64-pc-windows-gnu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Rust
      run: rustup toolchain add --profile minimal --target ${{ matrix.target }} stable

    - name: Set target variables
      shell: bash
      run: |
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
        echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

    - name: Show command used for Cargo
      shell: bash
      run: |
        echo "cargo command is: ${{ env.CARGO }}"
        echo "target flag is: ${{ env.TARGET_FLAGS }}"
        echo "target dir is: ${{ env.TARGET_DIR }}"

    - name: Build release binary
      shell: bash
      run: |
        cargo build --verbose --release --bin dbn-cli ${{ env.TARGET_FLAGS }}
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          bin="target/${{ matrix.target }}/release/dbn.exe"
        else
          bin="target/${{ matrix.target }}/release/dbn"
        fi
        echo "BIN=$bin" >> $GITHUB_ENV

    - name: Determine archive name
      shell: bash
      run: |
        version="${{ needs.create-release.outputs.version }}"
        echo "ARCHIVE=ripgrep-$version-${{ matrix.target }}" >> $GITHUB_ENV

    - name: Creating directory for archive
      shell: bash
      run: |
        mkdir -p "$ARCHIVE"/{complete,doc}
        cp "$BIN" "$ARCHIVE"/
        cp {rust/src/dbn-cli/README.md,LICENSE} "$ARCHIVE"/
        cp {CHANGELOG.md} "$ARCHIVE"/doc/

    - name: Build archive (Windows)
      shell: bash
      if: matrix.os == 'windows-latest'
      run: |
        7z a "$ARCHIVE.zip" "$ARCHIVE"
        certutil -hashfile "$ARCHIVE.zip" SHA256 > "$ARCHIVE.zip.sha256"
        echo "ASSET=$ARCHIVE.zip" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.zip.sha256" >> $GITHUB_ENV

    - name: Build archive (Unix)
      shell: bash
      if: matrix.os != 'windows-latest'
      run: |
        tar czf "$ARCHIVE.tar.gz" "$ARCHIVE"
        shasum -a 256 "$ARCHIVE.tar.gz" > "$ARCHIVE.tar.gz.sha256"
        echo "ASSET=$ARCHIVE.tar.gz" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.tar.gz.sha256" >> $GITHUB_ENV

    - name: Upload release archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        version="$(scripts/get_version.sh)"
        gh release upload "$version" ${{ env.ASSET }} ${{ env.ASSET_SUM }}
