name: release

# Release dbz-lib

on:
  push:
    branches: [ main ]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    name: build - Python ${{ matrix.python-version }} (${{ matrix.arch }} ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Rust setup
      - name: Set up Rust environment
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      # Cargo setup
      - name: Set up Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install build dependencies
      - name: Install build dependencies
        run: python -m pip install --upgrade pip setuptools wheel maturin

      # Run Cargo checks
      - name: Run cargo checks
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

      # Run tests
      - name: Run tests
        run: cargo test --all-features

      # Publish to PyPI
      - name: Publish to PyPI
        run: |
          cd src/dbz-lib
          maturin publish --features python --no-sdist --username databento --password ${{ secrets.MATURIN_PASSWORD }}
